title: Bryan Hohs
email: bryan@hohs.us
description: >-
  https://hohs.us

twitter_username: bryanhohs
github_username:  bryanhohs

baseurl: ""
url: "https://hohs.us"
permalink: /:title:output_ext

show_excerpts: false

google_analytics: UA-19916047-2

theme: minima

minima:
  date_format: "%m-%d-%Y"

sass:
  style: compressed

jekyll-minifier:
  uglifier_args:
    harmony: true

plugins:
 - jekyll-minifier
 - jekyll-seo-tag
