title: Bryan Hohs
email: bryan@hohs.us
description: >-
  https://hohs.us

twitter_username: bryanhohs
github_username:  bryanhohs

timezone: America/Chicago
baseurl: ""
url: "https://hohs.us"
permalink: /:title:output_ext

show_excerpts: false

minima:
  date_format: "%m-%d-%Y"

theme: minima

plugins:
 - jekyll-minifier
 - jekyll-seo-tag
